apiVersion: v1
kind: Secret
metadata:
    name: edge-test-auth
    namespace: edge-test
stringData:
    users: ENC[AES256_GCM,data:QOUBLFCYJEo9edyO4303nkfs1436jsracGPaggMad2Qn99K7zysBJLRT9r5KqHs=,iv:3XCivAUq3Qma602WVnBxksTURZSzSMTocL0WgGjA2ng=,tag:EEhZK9X1BtDNPeH5DV69bg==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFY5bUIzNEZHVXpsWEpk
            Vy92VVQ1UkJ5NnZtSFNhdXgzWjFzaGVYbWxJCm4xTmpjN1BFSTZVRHFXYzVya3pK
            ZFF4TUtuTHZmRXdvSVc5ZmlRNDJvdU0KLS0tIG1xY3dkRUVUTFp0WjNaU0lYdnZB
            Z3BzZDhmdDNQTm82cHlhNmhZSHhvMUkKwnkIZPqcTC5CALAXj/wcjRNh9UfpFR9T
            TV+1o8jVyONE74yfVoVEUFBeNP47tVE6GPlRZWPIAsNK+xCnzPydQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T09:08:34Z"
    mac: ENC[AES256_GCM,data:o2y/p6SCB9BCzSYzdV4WqURPjvxqFuIO/tJgqh8oe/Rmwr0+sPMokdRJs4OLWdp8J1WVPK/c+V15VLDsCWZxFy+vroGNqEF3PiFD9RLOMq/XARIvr07YLkuSAGPc8Dj8KxDJ7AAkTH7Z3dBUQtHjOCN3C7Ya56I1mEZe3Gb2dPk=,iv:/2sT/+NRjXMoaUSdOwLuHUHwN9bbQWQzm7HOjLSQOLs=,tag:OPSlandT1/03nf8+MKKJcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
