apiVersion: v1
kind: Secret
metadata:
    name: edge-test-auth
    namespace: edge-test
stringData:
    users: ENC[AES256_GCM,data:ATfnbNuHx9jrVZQAd8Yst24KoWaK54PDVLRgZZNL78iM32m9ikXKfYboIujvH6g=,iv:2wAV0kvTGzn6CKUORU1fR69EPUEURczhqWC7YbfNmXc=,tag:YLCXTeBUpL04f+Yk70Xfdg==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFY5bUIzNEZHVXpsWEpk
            Vy92VVQ1UkJ5NnZtSFNhdXgzWjFzaGVYbWxJCm4xTmpjN1BFSTZVRHFXYzVya3pK
            ZFF4TUtuTHZmRXdvSVc5ZmlRNDJvdU0KLS0tIG1xY3dkRUVUTFp0WjNaU0lYdnZB
            Z3BzZDhmdDNQTm82cHlhNmhZSHhvMUkKwnkIZPqcTC5CALAXj/wcjRNh9UfpFR9T
            TV+1o8jVyONE74yfVoVEUFBeNP47tVE6GPlRZWPIAsNK+xCnzPydQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T09:04:26Z"
    mac: ENC[AES256_GCM,data:qPiHiZSEM2+KhOHjyJnNlq8r+8qhGibT5MsXk3vxFzCHQDjvDI/4QoVDyop3tZfh8iXHvS5H8c8W3AD8kL0BXt0Pig2wJKWWXLpMe9sJDD76LwOHrt9CbbKvAdK35u9NLqH2zQOcmDmkb75HHmxYE8UUiZhcvGuL7l8uv/pY1Ds=,iv:9lHuvfBDPBj4ZQbQDpl9Dz2jaWrHNeMQnVuau+UnV2k=,tag:EyVBg5cenqOjL2ddzlvqrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
