apiVersion: v1
kind: Secret
metadata:
    name: edge-test-auth
    namespace: edge-test
stringData:
    users: ENC[AES256_GCM,data:G/wgMS1bA7T529GpMpkI6OslrfMd8ltl37bJ/j28/rg7DUPn2TUDjYLNE9yNXLs=,iv:eBaOkT7rPeohIT1UNTLvM0Dl9MbmGi1ICkiozp22Wrc=,tag:epDH3VFBhUAMEPean5IYKw==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFY5bUIzNEZHVXpsWEpk
            Vy92VVQ1UkJ5NnZtSFNhdXgzWjFzaGVYbWxJCm4xTmpjN1BFSTZVRHFXYzVya3pK
            ZFF4TUtuTHZmRXdvSVc5ZmlRNDJvdU0KLS0tIG1xY3dkRUVUTFp0WjNaU0lYdnZB
            Z3BzZDhmdDNQTm82cHlhNmhZSHhvMUkKwnkIZPqcTC5CALAXj/wcjRNh9UfpFR9T
            TV+1o8jVyONE74yfVoVEUFBeNP47tVE6GPlRZWPIAsNK+xCnzPydQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T09:04:00Z"
    mac: ENC[AES256_GCM,data:ammmElnWI187tVbqhMR1GvjpA0d1LJ4Kt7wQhFFksKLJLnxUOxJMQChPsvwbx3tBq1pXwjt/zg+z1n7FvlJDGTcFPw3wnF8Qmibicg/z86FJrw6jYDCOFzH8tArTbikfZ87iAeaAiZeNWC29yUDLjcyBlrD/19VRwFTVrBNxFs4=,iv:sBtS/Si/DDab91sPIwrX1CiiPM4zAjbUEm3vW7745pU=,tag:HA2mC0taQ6MBff2bx9XdZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
