apiVersion: v1
kind: Secret
metadata:
    name: home-ingest-credentials
    namespace: monitoring
type: Opaque
stringData:
    TEMPO_INGEST_USERNAME: ENC[AES256_GCM,data:vpn7LsvsUemmbw==,iv:U9gnFwegasMp3Zd/4pB8gO9Lh0r1PrBaER4U/M2vFMY=,tag:0xuqQQn6NW4XnWa5gDH/BA==,type:str]
    TEMPO_INGEST_PASSWORD: ENC[AES256_GCM,data:OC/IhBIJ7DMR0KOJGH0ZMGZx1mfomjdT50ILldx9UrsItdbU0KcC7K+E5O/h9nBS,iv:mO/qn0dlyZGwihqHxGL/pkKdWCVy4YaKeIS/dLXFaD4=,tag:bkdbTSfLewck7mSeOzMYTw==,type:str]
    THANOS_INGEST_USERNAME: ENC[AES256_GCM,data:TnX68yZXLr4SJg==,iv:vlIq4Oj60bQKEwKgsH5Tdg+kNP1O0hrq31aVVim0MUI=,tag:YZZePEVdEZRf+cFMD0/Q8A==,type:str]
    THANOS_INGEST_PASSWORD: ENC[AES256_GCM,data:DQ0rQp2pVJLG0827TGcalZHhDrFkBOGL9uXBy8iWfucu6gUfn9TFsBIcYC240A5ORxftad5cL7l/ztyqRay1PQ==,iv:FCW7LqXwP/wso9X6nH/uaSXIBmBM6yz6gTTzuuum7Zo=,tag:iIjadNl6kEe+nNFDQdMjxw==,type:str]
    LOKI_INGEST_USERNAME: ENC[AES256_GCM,data:r6rHXjUMEWMsAQ==,iv:64IsSEphVglP9AlHMzH5akVUN4buHHiSsM7goK7+B38=,tag:Oa5XK5cE5qNPE9lpgWkkSA==,type:str]
    LOKI_INGEST_PASSWORD: ENC[AES256_GCM,data:W5FSZyLllZVJG6IMAbfDYyzfGcEH2NpecTGnGv6OnLuVM75PveeigfGg8NxNOIjtJ6oMgM3hLCDWOB9u9IJOnA==,iv:TquCK1wi0x4QhOF3H3tbIDnqB889oJTa0Jw72XxW2RQ=,tag:rUXDATg/9tg65es1OClrnw==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Nk4zbkFPRWFiUUdVQXhj
            eU5YYjhDUEh6aG1QYmEyblZaNnZ3NjFnMzNZCkRnVmcyVmNCVmJCOHcwbElnVzhO
            YUFrN3VLeTRyMkVLUjlKZnkyNG50dncKLS0tIGpqOVplMktVVjdjSENEbHdycXFo
            MjhTdG9PaVBpckFGTzdEZm5sczFySVEK8jj5i5xFfed+5jLywr6ZPFtSPrH6y1/J
            lxQtFUfMCLKotaFCoYMyRc2sSfE23ikbSJ3hQeV282HxPciPC0m5pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T18:29:22Z"
    mac: ENC[AES256_GCM,data:WRzUPgzRDR4qN/0CA29MJA+GHJlX7fItAWZEhMteLGKjKyQoEat13pSRH1gbG0/smpuhtBw7YEGeXXBiAcdQm7IfPFY/jFURuTxeJ2GvweULAaeRekGMSE5GKJHbvs9ODGMXgPTGf92iZsjwmWtWxfwtGaFEomkfO42JIVUdxh0=,iv:6DRAuLQbdE86nkQshKRjrT7VfDZcbN5Mqm8OqxvgP3E=,tag:H5boUDtSIDZNjBepJZ1ylg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
