apiVersion: v1
kind: Secret
metadata:
    name: home-ingest-credentials
    namespace: monitoring
stringData:
    LOGS_INGEST_PASSWORD: ENC[AES256_GCM,data:qem0MHYCgMsowgdeFbqe2KbCFza5LDberDINIK1pdVxBL6oEI6RtPGBeU5bcAybc75KHcVI3m4RNA5MIZGLSvg==,iv:EHJ8NkCssjdhwduI0r8rC2tVJEC3wkGnxEWlWGwLOEc=,tag:34EHQEWVpBeIo60RJ4Il3w==,type:str]
    LOGS_INGEST_USERNAME: ENC[AES256_GCM,data:+bbmjpZI4aNsrA==,iv:I5X+cSd1bUKpco4A4qRKQHZB2b+Pqru19jh7dUuYz5Y=,tag:qaCPRJAYp6/NK4JqHN0A7Q==,type:str]
    METRICS_INGEST_PASSWORD: ENC[AES256_GCM,data:3X0Kf3Tv9qU+5xOhLUZ44d2ovVg53N/zPF9fEMJlDak31fjrc1j0qyLn+AVcgCFMMRYFphsZ45CJQ1y8FzBP1A==,iv:lOY9upytUnviC/ZkXvoUjORboGxpf8URmlQ2Qs8tcu8=,tag:WtrQnl2b4H6aOoQpldg6sw==,type:str]
    METRICS_INGEST_USERNAME: ENC[AES256_GCM,data:/QMBl9Xp1Mz9iA==,iv:O9RnsnzEHQkuzPO12lvPNbmda/Ej4KN0YXWJJyxV25g=,tag:g27hZn+3KjJsQiSyfY7kCw==,type:str]
    TRACES_INGEST_PASSWORD: ENC[AES256_GCM,data:c0HiyX4LSdjk16EwEO5r51eVSm3gLLOBP8cnpcJk0BY1B4v92js3Af8hVdTZvpbA,iv:rSl2i5HsRDaS9gfhlI7tM9CcjkM/92wEuyB3ibfXGj0=,tag:MPKyFrdoVRAfAysyujambQ==,type:str]
    TRACES_INGEST_USERNAME: ENC[AES256_GCM,data:H7vpdvHTXwrFFg==,iv:efCFDvFwD/hHyQD13DjfAQj6PqDLOBBXaWIw52afg80=,tag:WPROqZeJd2Vr8tjTGhEs+A==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONnprYUlEREc4dWVLTWVZ
            VWxWL1dSV0tSL2hsaERLREdCS0MzTis1NUd3CnJ3akI0QUxlU25sdjMrd1NwdEVW
            VGxLTFp3RE1XL0xGWEttSnRhSUNNNEkKLS0tIHBSVkgrVXdoNi9vWFliSjdJS0pY
            UW5CUWE5cUd3cjZsdEhoaVI2dHdPTTQKqbE5Y1NmnQ6c0YQRBoo6K2Hoat5F8Ftj
            Wn64PnV28yYoa/yDMesRN8HcnG7AA1jM8vQuWaYsfruns2AeFaYeFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T09:35:11Z"
    mac: ENC[AES256_GCM,data:tXs0j98Y1+sLad8ZCdV28cE4B72Qh1lRenj1TssC5OiehQ83RegWiKYI3Z5hPyyO9hZ9oa0SZtviEBjxwQYnQtkob1zKJhkqlYi05ThTgSmdMyIKHDRll8S0ABNfsM7h4k4K2ux0+i/id01YC86g9pepeqaUWpo6jJ42EI2deyo=,iv:2N3COfrk9nMXRssh6IJvgcIbQ5WPTGQ6YpDFNwpQ5Jw=,tag:pZzz1TCsYN7nnzHGwTcXwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
