apiVersion: v1
kind: Secret
metadata:
    name: home-ingest-credentials
    namespace: monitoring
type: Opaque
stringData:
    THANOS_INGEST_USERNAME: ENC[AES256_GCM,data:TBL23+GXEusCgQ==,iv:vrqoin8BAuxB41nDPzOiFYmk3fn7DaXkBQsUeMInVhU=,tag:dRogIITj3L9vdYrU8ewo6w==,type:str]
    THANOS_INGEST_PASSWORD: ENC[AES256_GCM,data:URepzakjrZIOFqV1DheFLLY2G04h1zX5o2twFSvsPrWMEsZc/XKBk+7V2lmnJfYcVihY/nf4QazUktoVPTIdCA==,iv:q3BMoIY+6W7xWF4bwEenjlLA30sd/ICISIqDKgOpBLI=,tag:yedwIgilSzCT0Ie8oltEgg==,type:str]
    LOKI_INGEST_USERNAME: ENC[AES256_GCM,data:kq00IvWfbTslOw==,iv:vtyekrQkPIaBm2LLtgrc41FYZjZxSDdnoL5CqiyGnsA=,tag:vDKwcWKFpvP28VI830GQbQ==,type:str]
    LOKI_INGEST_PASSWORD: ENC[AES256_GCM,data:5iHyPzh0KDLAz49shZatTHr/0ga5o65pILLX0ZM8GzQ9e95LV3c+aXyFKJXaOC5Q1ZFf7SvsPeCcJPuBOigi6A==,iv:iOYpUsDMWo7b5tzRf/ELNzdBtNiceoQaG3+YHSmmMRM=,tag:r6ce/lernQV8T6KX4TZhsw==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SDVNNWZMV1BWU2R1SFMy
            ZFNmNmpHT2s4UkEwRUZKc0hDKzI5dTJIcnc4Cnp5WmtOamR2MHZFcVdKQ0Y3b3NX
            SmY1c3ZaM0RzcVQzMHIxTUM5Nk5pc28KLS0tIFRUVGg0LzhobWZ5U3hUbTZUYXZY
            cFJ3UlZwaHNIMzFUT0NFYlNOZXFDTWMKOT2alhzr14mYLmx8CiHYSYjacPFrGuOg
            KPQ0tpcAkkN6b8z8Ff/nsWLflkFiZoj5N8lLBghi+8u5gsXlo9MyBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T10:49:19Z"
    mac: ENC[AES256_GCM,data:Xxz9RH7I0q75RUTm/L9oBJ2oL84tiu92iVSNQXTYQn5b2wpfTlhK77XpIbwPlSLd44nBa8jzVkU2F8S2A01wwctlspp/isvi+Vajzx8pctkKC2YmEntFqcQY9i8IZySO08/1Q/+m6ovOCV2cNX/o2k1EjiRyWcTVaGQziNB27CM=,iv:tzm2ST8jdIKNI/HJQ61IaA5pa9QWAwVzj0y+s7JEQ4E=,tag:iQsy09EAQCZQ5lbPwGR7/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
