apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee2mqtt-cloud
  namespace: zigbee2mqtt
spec:
  secretName: zigbee2mqtt-cloud-tls
  dnsNames:
    - zigbee.calcifer.tech
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-azure
