apiVersion: v1
kind: Secret
metadata:
    name: azuredns-config
    namespace: cert-manager
stringData:
    client-secret: ENC[AES256_GCM,data:el9IEoJ3jQZrcxSTr78/x+32vIqtTom2yjkt6miNaPWYhBnBOrMwXw==,iv:otjjVoxcIA++IH5M67+/exaw/HoCwev4wXbbvyFj2Wg=,tag:pbCUtXVUBPt3ZdqWmAieug==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndlVIOWNQSGszUnJxYlh4
            UWR0TWZaTXJzYS9oWk5TWk5nL1hJNkhGUFNBClJ6ell2OGR3NEZSYmZXaC9MZnA4
            VWw1dGpCWlo0UmhmWWFNdHhQbjJWMDAKLS0tIDc5bFRPcnQvTE1BcFBpRDZ1dEp1
            Q1J6YnRwVHBLS3FHWWwrUnhFbU5BRXcKXY7whP7IwJaUsnskTMqZIgBVK44pcMT7
            542F04Ujznk+g1mR1hwfZVr5oRRpe41C601KWCMSc9OoV3J/m2hCDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T20:42:10Z"
    mac: ENC[AES256_GCM,data:V0kPa0L5oHt4y5KRRoqoSkQ2wLc88SIoeae9uqc3x1/KW2KQM01Az0RWPnC+oCwPGFWszeGavXlYJg5Vf0vj8ZAjA+EvHvZlVEpAWspbqEGx5dcrbrwBanjvpQjMpgVx7VTHP5QUvxBiSJtmNtu2rzGt0JHQJLpSavGcgwfFWkE=,iv:vPzHN4h4B5wxnG+2Bw3rO4Hbb2BrLHHpxOrbIWzRgKM=,tag:vUl3zpyyDe9/D5tE8hIAPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
