apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-azure
spec:
  acme:
    email: dem.gianluigi@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-azure-account-key
    solvers:
      - dns01:
          azureDNS:
            clientID: cb4edcd4-8397-4577-8253-3974926a83cc
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            subscriptionID: 13339ead-c73d-4697-a75f-25ff6b3d8dd6
            tenantID: 6ab554b0-ff6e-47a0-986c-3bad955c4694
            resourceGroupName: rg-calcifer
            hostedZoneName: calcifer.tech
            environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-azure
spec:
  acme:
    email: dem.gianluigi@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-azure-account-key
    solvers:
      - dns01:
          azureDNS:
            clientID: cb4edcd4-8397-4577-8253-3974926a83cc
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            subscriptionID: 13339ead-c73d-4697-a75f-25ff6b3d8dd6
            tenantID: 6ab554b0-ff6e-47a0-986c-3bad955c4694
            resourceGroupName: rg-calcifer
            hostedZoneName: calcifer.tech
            environment: AzurePublicCloud
