apiVersion: v1
kind: Service
metadata:
  name: wyoming-azure-tts
  namespace: voice-assistant
  labels:
    app.kubernetes.io/name: wyoming-azure-tts
    app.kubernetes.io/part-of: voice-assistant
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wyoming-azure-tts
  ports:
    - name: wyoming
      port: 10200
      targetPort: wyoming
      protocol: TCP
