apiVersion: v1
kind: Secret
metadata:
    name: azure-speech
    namespace: voice-assistant
type: Opaque
stringData:
    AZURE_SERVICE_REGION: ENC[AES256_GCM,data:BkDj1l01ecjJ+g==,iv:Al4RTXdslyyGsdYTDFjZsgcjajaxGYBFBXWud2koRB0=,tag:/HdEDAHx4x4Qfe0Zi7ROGw==,type:str]
    AZURE_SUBSCRIPTION_KEY: ENC[AES256_GCM,data:AoV1b4XKIpyZE8iwGv42HTxaP5GpMR9HwDBBrcezpCbxwP4cFHwje2EHqdBuTNX0vr+8NaeYppQMhO2yBxGCqNd72Fy2+M4GwkdtonCoGJaaIJVY,iv:plFYk5bL8uvEMD59/I2CUHg94IkJaTfFEZFI2JLyy8w=,tag:1a37byY3peEfN6IPT7ryFA==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S2F5WXdCWFFtRGVEaUFz
            dHhUenBMeFhINmtjTy95a3NSMTZYTERtL0VJCnhDby90bVhZVUNsUlBXYXBtdFky
            NkFXRWlLYVVIQStQSVRycGoxWWdYWlkKLS0tIDNCVStxRm5GZkZOL0ZWTExzZUxU
            TTJMTFRVd216b2t4WWx1d0RPSUlBbEkK+4nWi45qeCA8gjCkGpS6p8WWqT98hI2k
            AWd1KPKSNXaHdWWuEJAfrVqp5lQ2wm2imMf3JKbG92qrnIRJfZGGeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T08:22:58Z"
    mac: ENC[AES256_GCM,data:32cYZqn1Uzu6jGckCrGI5LvF/wI1k8LzFocOJpMpLfFhagMB1d7de/uZpWmiTfgcnPrg1Tx/vcVSornTUJrV8znKPHWSEl4EbtqokQ5iD8b/mbWKQmmb5vBMIkwPU4OHqxV3ZosocnapRSStfpmvqxuAyZlRJGkGbXrvZ3JOspM=,iv:dg8ncN/TZtO8jgaOhVlSepdjvkXDuxeeKGsCnZeCADQ=,tag:/MseGwJF4xhtdypO2QKuuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
