apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authorization-server
  namespace: lan-dns
spec:
  endpoints:
    - dnsName: auth.calcifer.tech
      recordType: A
      recordTTL: 30
      targets:
        - 192.168.0.102
    - dnsName: auth-home.calcifer.tech
      recordType: A
      recordTTL: 30
      targets:
        - 192.168.0.102
