apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authorization-server
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/apps/authorization-server/overlays/home
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: cert-manager-config
    - name: lan-dns-install
