apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-transit
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/calcifer-home/infrastructure/private-transit
  prune: true
  wait: false
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
