apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepositories.yaml
  - helmreleases.yaml
  - thanos-objstore.sops.yaml
  - loki-objstore.sops.yaml
  - grafana-admin.sops.yaml
  - thanos-receive-network-policy.yaml
  - thanos-home-ingest-certificate.yaml
  - loki-home-ingest-certificate.yaml
  - tempo-home-ingest-certificate.yaml
  - thanos-home-ingest-auth.sops.yaml
  - loki-home-ingest-auth.sops.yaml
  - tempo-home-ingest-auth.sops.yaml
  - home-ingest-traefik.yaml
  - home-ingest-nodeport.yaml
  - loki-ingress-network-policy.yaml
  - victoria-traces-ingress-network-policy.yaml
