apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logs-home-ingest
  namespace: monitoring
spec:
  secretName: logs-home-ingest-tls
  dnsNames:
    - logs-ingest.calcifer.tech
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-azure
