apiVersion: v1
kind: Secret
metadata:
    name: loki-objstore
    namespace: monitoring
type: Opaque
stringData:
    AZURE_TENANT_ID: ENC[AES256_GCM,data:WmkcprMgw5wS5v19jqFavgatXDA5blOTVNVdDxx0s0buQKQ/,iv:8bRitVqYqLauqs7IVSzghBm0Kn419cSAfya/Rd+laxQ=,tag:de3YO7k7NwcyfxDypVqixQ==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:XEnJMEQ8ytTe0Vr4qbK8ePxal2nIuHBlTLMzlUAt91koqv+Q,iv:5ZBpRSH0B0BqIUsKr/nmuu+1ddHHdNZDdeQH0nFDAR4=,tag:ubC4LRTwmjv3NYpqPiyKeA==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:UKOvbD6jJU8xI8dhhj9LSaUi2A5ivd8FAiomaPBOpqeumDp5/xsIhQ==,iv:VeXS093e4BcrrhhtgxuJSi8vKlK2F/kBpDbZhD7agfo=,tag:V9ZKOTXzodLSSaNtLeBuaQ==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNEpSV0F6WDRjWU5UZ3hx
            RjBmN3poQjdDYUx3RDQrNDBKZWZ1RmkwTGlzCnd4K09sZ1plaEVaTUZ6OU5wV3d2
            MWIrNTRNRmtUVzZscVpFWGVabXkrSUkKLS0tIDF3cEdiVnB5TWJTQ01qTUFvSHd2
            VEs4dXVZSmJTZWYxZU5oK3BuUDBZdkUK4YWTWrIRbThjnTkCjQgFpzgQ4IMeQkRy
            k2Niom2tO7HJsi0G0a1Gq/MuiQFvwcIt++cKO0stSgB6zFZu8J1yeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T08:21:20Z"
    mac: ENC[AES256_GCM,data:05QdpNAjKva+v9tIrZkUpIIpEGtFy910LKkSvvW3M+AHdhBZmowF/S67ELEEeucd+dLEjw2dgOMb1OJLxOP8mij6aipdwcosTlnqtvzCnkUQmFnhdeNvBK8eusRKLJkRsxVTw5FqN2NJs9O9NGDzcAAV7RhcG8g9yLcxCLl9UrI=,iv:DUSsqi6Ldl4ouk/3GIVC6WfqAuOnIYL09rpU54SVZHs=,tag:mH/guO5hE9XxILeUqc+hDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
