apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-home-ingest
  namespace: monitoring
spec:
  secretName: loki-home-ingest-tls
  dnsNames:
    - loki-ingest.calcifer.tech
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-azure
