apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-home-ingest
  namespace: monitoring
spec:
  secretName: metrics-home-ingest-tls
  dnsNames:
    - metrics-ingest.calcifer.tech
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-azure
