apiVersion: v1
kind: Secret
metadata:
    name: tempo-home-ingest-auth
    namespace: monitoring
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:OkBtnHEKBAb0X2e+JsXzNI2A485ZW8jFI89kIEBDjvwAifJ0PHJD9IRmxRPHfIv70dZB1D3OTbM+V3df5ZxjObhk2HqUKuY=,iv:M/QLYfkh+WWhU8wF1DJtuJPprwGFINq52GMZ+OKnbdU=,tag:2WdKNnf0dIVFoAINGf8R4g==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReVhzT1Q5cmZsbUZwQ3ha
            MG9Rdk9mUFFQcksxY3pmNWQ4Z0kxakJjOWhBCk1uUUtpTk1IQjdWNFJiWFBsZFdu
            U3VpTVh4TUdBL1hvblZ6aWYybmpqR1UKLS0tIHdSMVZQV0xraU9WUUZjcEZET1c3
            b3hBZElkdkRMZ2t3RENXQVQrTlVtTDAK4rfwEBgBdHmAwJyfF1j966jBmY+CGeHF
            dxW6xrBJkvTBYnq9WI/QJVZ08IfsvxOqjw5IjgIBl5QdYL+GT85T3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T18:29:22Z"
    mac: ENC[AES256_GCM,data:WQjhIT9dgU6Zq31IprHEYjwdVEzkgiLNY3nHUj7r4xzuu9QGCjY1lleAm0+lweHJOCn4M4yMz+OtWu1EZbgBM3UJjtxKvyXi61CPt3C/NRRx8xLJIKUKrtXNDeaUHjTkbeuvi27Y+/KfnZWJv/vMMxcW4JbDCUSVktdB4xXrwBU=,iv:vObGb8y2NGzd+E/qgYy5lIjViojvJi0xQW1BNSopFXc=,tag:2cX3I9giTaC3d2eSZ+tIBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
