apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:z3gVo0CeQbKwaf/x3nm3ESWhPowWTlkgDSgHpTIbMdrTaDCrFh4hwzHzYJhHOKF7CkATLn/719U+jQOgq1wtiy+iSdipFd0QxGoLBVk36pfQVThjby0bOWQQbkLZuTCPm/YSQMPrYXhx0KTP+KEHvK5VCv0PqBKCz9oljyqG8zB8eeUzxYE1mSOdA4nFESXzXU53F21wBiDMibSQdGwJ4WnjfSvmJqqwJUHxjrS2or8np8tTkRckO4UoDkmj2/io58xvSzsqMrDFn/YsOrnE4x+OpAwT4eRxv/vgTz/Cw+MUWynIbEVftpMjKG+lF3Ooe9RjZNDRvd2LCGDM5rZyNYiBHgPXfc0931nEP56jnig1IeQuxBNBHOb0NFDONWj0j3njWZTUf899KkfRIzQp2QXwvvEt6gx2r0v0LfJQGLQEdxmRlcI4K9hiWoryb/WT2dgql1sQ3UpjghsqXJV+vTPOCTwQfuPBguvf8oVtys5Z9CTuYC3EVYvjzE7WFv/ING3BdSFS/9kJWT5Bm9h3lK/WgYXctENa3z4G6KZ/2RYo0OBfTsdnYK0bYoULMk51Wfg0kh8=,iv:4wgtl+KQpaDin5qDe1uzConec/zfib6DHCIWuALp3NA=,tag:v1M2VtO6REYx7ynVnuB7+Q==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2RLQjM0R0l3c3dQS1E5
            cEJuY2ljWUZZcDhqR3Q5L0JLTm1DbmdLWmpZCk9PRHdhQllMaFFmblpGWXc2UDBJ
            UXJpd2JkZkFSaXgxU21DNVVqSk5DWm8KLS0tIDZvZ3M3MGV0UUdCb0Yyb2NLaTZN
            M3N1aFIzQmEzVXZCb0g2MXY1Rk14M0kKQaiRBb7JRo5mJcqGNs3xIxnRUyCSFaB+
            8RIVx6pF1+DV7ZdxsfN9ow1zG2/t0qUos66RwdBm/B+epBi/0bxG4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T22:19:37Z"
    mac: ENC[AES256_GCM,data:rDPQ0b5V3tWbMlpSoWtW1qFx4OYFf8/LqmthKUomNhswXcmSDsIXAh2CDxMeA5RMp2sGkb91hNd8t5Oyn++bGvruCfnB4r0I5rFlvqfX1hCn5fA9+77qqTAflqEOoy0aMSCot6EJZPxHxVS/UTOyW6CY+EQ+6WkdVH+sAH1u6aA=,iv:zKr6vwddZoFcn5DS7gxQxrdqdMPm6Y3c5Dne6ElBZ0M=,tag:8/t0RPHPfJw5YYxTdIRIEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
