apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: monitoring
stringData:
    cloud: ENC[AES256_GCM,data:xkxUrTA82tfPIalWYl/zAlSsm55cy6ULke/4MRR8h3UyWEcrDHcIaSydEfpRId/z8TH55VhidJ1dFZvFVnZrZ7Zg7jcDzdGvLT/5NoxkR0ZEzpDiyQJzCbP5tkvUZI3vjYJfh4CcnAv1bZmdNTqxQxZNZO15WIrMHEqSWXGmbeZtwtiZ5QL4D/DUGMaus4gLZDbrldbJxfuYmExnoP9HnmZ3XUmz8JjSy3zTOaliN+nYZGzWa1bdixf0Go6AUTxX/HkDtIHtv4bvRmw+0+DGEWeLHrcIjst/MAeZ2aV3pelf3Yv59SjGn3kRkurh91zA9wVs8ixRisPXpJhM0sJdcW7kRfpgrpnSAQ5qaeldIbkeZhCuj0Vk/6Enssb+RgZKhDY+Ds7Jq42paEhzC/tYv4pcFck=,iv:yef42b/h30jxSoT+sL5n0aQvz0ZFfpaXqKjzFhl4+2A=,tag:iSj3MCotR2Anbliz14rSSQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdDFuL1FlTEtYOVBmNmtY
            Y2ZLQnhkYlNaR2NWcmllaG1CZThyYk95b1hvCnZmemNqd1ZQcDA4b2NsYXlpa2Vn
            YzlVeXJ4NE1ZRnVsQnVwbnVhaUtyNncKLS0tIGtmeTFmeWtnQlZFN3c2VXhNRSth
            T3lPMzB1T25vdXRJWms3Ylg1dk53NFkKk1TF0yqkzYpoojp+QPa/k/MsQQ9YpBRf
            JTVS3ZKNGCCqm2SecSkIjqolY4cBg3QYZo54bLR6/6W/0zG2jRh2eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T08:33:22Z"
    mac: ENC[AES256_GCM,data:3rgf9F6ovtNdeW7FdJRK6oqUwrYFjQtPoY42jAH2ls1agMQvsx8y8iGvS+ZKLDIZidtDgTPD75KmHax4p+/OAFRcfJ3PqrCu3n9IhlWN7m0R4OLEqiQs/lK8Jkp5f1n1BYFUxwog+mLJuXreSF0BJtlrO95OStF5uo9iJE8s6Gg=,iv:7s01D8RcTD/Wc5nqvXqobdluYdrKrwuGBpgKvMGgPQI=,tag:qj8/ubrhePB3nKBf2Y/Aig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
