apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: monitoring
stringData:
    cloud: ENC[AES256_GCM,data:8THfMku/p+uZPdEDrcK43MgtZ3Zvd/u4Qr63cpzWryoOA58KMv04MQKS9Q8YmS05YTglI8hzf6t+hY4nBhA7ZCtdVF0tN2FL8YGhBuElMSaGltogCUKa1hGj84UFoFF11yy8ChPI8uiTnSgYiQpqOjQbjvYJFPVx7DDMG4BNvF+9tPFT5qsU4Y/8Tg1jgyW2LwS1gxBXBkyeEKqDV90CgQ5MdILV+b1dcCEQERW9HUIWz9Q+YaisYOoYKOfBF/a3uQyxiFvJLedkdYNLxwH6vAJjq5l+v1jIYgwIWN8IOAazv7tR9Rrw7JXPQzrMUdpBtDYKqFFVeFhl9G2lI+n6NpCYRKTP8/KMyayFeoPDv11IjLNKQOjZjzEt+ANFZfR371VaUYQ=,iv:ypFIW5YIGIVUlGzSTeUWGqT+PMF105VDGfvAhlAY82g=,tag:ELtc5XtDO/GfKnRsw/zZ3w==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcUtnT2c2ZEs3bVhVVyt0
            bjgzelh0MklhQVEydk9hbm9XOU1SU1pQb2tnCm9VR0VORTE4K2kzQ05FMEdNUGh2
            MkxxbTdMdFh2eEdhTnUrVnpia3BlVkkKLS0tIGJmSW5MVW84anBrUkcyV3dPSDVT
            LzNUUkRHblFnbmhWaEpBTEc5SnBZQ2sKQ4a5xU0bqM1PGyh9H+T7LQ8F4SSWc8E6
            zIqDxia9j8Uz7UEXz13J8Y3e3vGBYsUgxPYOPDYW3mOQ/BPAm3Ue5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T08:31:40Z"
    mac: ENC[AES256_GCM,data:cZ5vm1Og8c1/OX7ZkFVP+bN1ca+gCzXwAMo8ERjn+Gv4duOuFCYgi9jC1TN9O17j1mBaXLpyoNNvVmReMeWpc/PZqdp00gP6+rxgJHm+fM5Ny4PVTrDW0/QH6gGcIOhTMIbwgEsul4ei9AN+D3QSuTc0saFuFURiWDZNdDsYf5k=,iv:fZiyk21UIo5U1D8KtfoXoWosF1t3B/s7Tj9bnwiqWfY=,tag:xcaw2Pgi/AWJJIKftpz+9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
