apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:SerAX0gCtM+sF8P7GvHATkKWU4BNZGVzv0uqS7d06xQyvh8Bomk2SfpB4P9IgDXVR2yr2fTVs3uVI5QAAqAABg==,iv:UvV9nfn9KZozDIyZObBK5c0t4zlBjzDGmgSxslAAvqs=,tag:n6i9JI18/FPEVJzfKOrCCA==,type:str]
    HOMEPAGE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:LO5HNl50o12xpkaNivww6D3gn14TumxwNpiSZRIh6ZgaJ/pH6zf6U+Qg0He3jJLMUY6dQa9hInXMvYebGfRhGQ==,iv:9JNdau21nfjWvlbjG1ElaUnbjYqox7rHb8Wl21w9C0o=,tag:ziYsOYpESiXTbvGz7uEtoQ==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiODNQMlI1b1AzZWFRd3NV
            bFEvYmRzait0Q1hNa1YxdHVNck9NTjBpWHpZClVCSm5pbUNLRUQvSEN0OEJYODBQ
            dVNPOVp5NG4zaDhpekZEOElvNEJSU2sKLS0tIC9vSE1tNk45OUJlVHNKVTJlU2hk
            aE9vMlQ2QWtZZktTT2V0N1R3dFZBajQKdJnOYGtvWD5G5EH+zP5BlbicT+YuTH++
            PNL03fB4w2Ebnakac9EZbrhj/9kDyU+nhWOcIEq3TrSH5GPp3sx1+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T11:49:41Z"
    mac: ENC[AES256_GCM,data:MzuPxjfIvSzoHIaaZL6NH+kUIU5wM0/00MLsAPvAE/TH4lNI6czqwdVOBvhF4+1+VHGa5S8kUzVlbtz0Tjo+JX+pLGjrkea2P7ta/1TOHQSo/py+BTQB7U0f+hmH0hRN++MLyS9thj+O6YN/1/Eroq0yGvslTkvFa7NC51krmK8=,iv:bMVmrcyvFN987ytyZhj5/9PA/9IhdyObsu9qBIp1DCE=,tag:ACRrnbjkZB9ln9xM7iTu4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
