apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prepare-pvc-binding.yaml
  - home-assistant-restore.yaml
  - home-assistant-mqtt-endpoint-migration.yaml
  - zigbee2mqtt-restore.yaml
