apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-credentials
    namespace: mqtt
type: Opaque
stringData:
    zigbee2mqtt-username: ENC[AES256_GCM,data:Pf2eWfAtJL2xa8c=,iv:eH6A7P+GfpaWUS0mctY+CUoM7YR3N8Fj7GPbt1cKqfQ=,tag:wNlQgxZV1mfInZMdjdtBxw==,type:str]
    zigbee2mqtt-password: ENC[AES256_GCM,data:5T73TkK8+ncNnrVJ3wR9d4y2NHbIyaNQmror+SNIHLzYVxj3hCzEW/HFbw==,iv:EIRx0gasSg5E4eUAgm/M5WiDBqV6PcyAjF5XjpsfieI=,tag:aEU7SsqWdcsPofs9otm1Pg==,type:str]
    homeassistant-username: ENC[AES256_GCM,data:bU4MTqvsprr6dXrGrw==,iv:508yLuU/y9qLwv5o/8gWFd3CsEdGPx9m6r/iDy/COCc=,tag:o/NX1s+Vef9hZPikNS6gVA==,type:str]
    homeassistant-password: ENC[AES256_GCM,data:7m3JAJMT7TsgtbM65FqgOqFSM3iYQ/ixOilM0lv38+vLii0wp8WzNjyCOA==,iv:JXxtFt3hD4EVIVmuYaZ3Tcxo9gE+O42uEyAfXD+FDzc=,tag:EI2zEo7Wh3qdkfnKS1Wipg==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a0txVHJ0aDcrT2ZNelpT
            QjdMMjV1cURRaGd2TFNGM2czQi9Xb0tUUzBRCjBpZWxiL1pVbEEvbjNZOUo3RWNS
            bVhIbjc3TVBWaDV6V2NNaUZPSFhZN0UKLS0tIFpMaGhTWTRzZVEybThoM2FUdGwy
            a0o2MTdOYWNkVUg4bS9MbnNJVS9rbEUKk45advwKs5wyvOAGkua1YJ8swGw+DXAo
            9QTxBVv7F3n7+Y4comilwrNkHTcKNMvlHSX6VLhIKvjdnyJGexf9yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T15:14:04Z"
    mac: ENC[AES256_GCM,data:Kpv6LE4g1K/8Mj2bM30zJ2nlM+maAJuIz55jGqJu6WczAKPgHJJBAjD7e2COd2N6kre2Ua0dV9vDCMCT/DEkJfG3fY0fWVODctw1FZR5T9CgmSxPVQlQyEBZaCnA47ATOG5WwaP5frYSjbJoXNHBQIA/f35UL7/Hb6ePO9KLHck=,iv:vvfQwXAXG0+SxJau0cEJIlR/+putLqufreBRH5//bQ0=,tag:xPTiiskff/hu8K2bhMjKAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
