apiVersion: v1
data:
    RAGE_QUIT_CLIENT_SECRET: ENC[AES256_GCM,data:6WMpQzKg/g+cTWKUaaTqrF9shpveoJ7gjSl7BDfI5nWsJawgqRQ0xI2uF5Gep2wqPLN5jTakY+PUViDucZ/1wxCkedt4gga4Mym8jzFAWCw4F72ey25JlA==,iv:tvnUrx0MkgpnT//1/1KFbTRxkIEHfeuOidqWGzvTqRw=,tag:3uw11juBUWHDkyDK7pMvAg==,type:str]
kind: Secret
metadata:
    name: rage-quit-secrets
    namespace: web
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cVFtQnlDSWZhby8xSC92
            ZHNIUEJFemd0VkQ0VFJrQ3ZYSU5xeXZSS0dnClZhbU5JcGVGQlFnd3BYR0hydkQr
            RGNtaWxiYkdxUFpXR2tiWGFYSHpwNnMKLS0tIFZJemNkTjNCd1A2eUl5dG1xR0N2
            bmVJMGNIcFFnVmpyMEpHQ2ZmMnp2VVUKzBly6BtSCtcAdNMedx9D/No3xtcTha7E
            ABz221szCgmoXShDaov8aiHN6PSYPKQCZ8CH5CLxmqhU0eIIKFNt9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T15:42:56Z"
    mac: ENC[AES256_GCM,data:pOD7SpVs3VRHEh2mwVm4DXp4drpqCpV5WJ3lIKKu5JByuencXfsKbMMB9nVY7OzkRKQKdJVO2Es+IbDD/bxh91fvndl/OHHqM3/aMKJVFlgeV+4IRda1rRh+Kv8loj7M/inmYsHrpLuqlRNUvINEaIznBCygMZ+x6Q6TlbLaaJs=,iv:JUzuQPdHAN01TBmGxW/KPImiM3lhyr48J9kvO6qI5KY=,tag:4sHztIWtZ/+JlT7N3rtcWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
