apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authorization-server-ingress
  namespace: authorization
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: authorization-server
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8080
