"""
Env Command - Manage environment configuration.

Reads from local .env file, generates secrets if needed,
prompts for external credentials, and pushes to server.
"""

import argparse
import secrets
import subprocess
from pathlib import Path
from typing import List, Dict, Optional

CLI_DIR = Path(__file__).parent.parent.resolve()


# Environment variable definitions
ENV_VARS = {
    "cloud": {
        "general": {
            "COMPOSE_PROJECT_NAME": ("calcifer-cloud", "Docker Compose project name"),
            "ENVIRONMENT": ("cloud", "Environment name"),
            "DOMAIN": ("dmgiangi.dev", "Domain for services"),
            "DATA_DIR": ("/var/lib/calcifer/cloud", "Data directory for volumes"),
            "CERTS_DIR": ("/opt/certs", "Certificates directory (separate for safety)"),
        },
        "grafana": {
            "GRAFANA_ADMIN_USER": ("admin", "Grafana admin username"),
            "GRAFANA_ADMIN_PASSWORD": ("auto", "Grafana admin password"),
        },
        "keycloak": {
            "KEYCLOAK_ADMIN": ("admin", "Keycloak admin username"),
            "KEYCLOAK_ADMIN_PASSWORD": ("auto", "Keycloak admin password"),
            "KEYCLOAK_CLIENT_ID": ("calcifer-gateway", "OAuth client ID"),
            "KEYCLOAK_CLIENT_SECRET": ("auto", "OAuth client secret"),
        },
        "api_access": {
            "API_CLIENT_ID": ("calcifer-api", "API client ID for M2M access"),
            "API_CLIENT_SECRET": ("auto", "API client secret for M2M access"),
        },
        "forward_auth": {
            "FORWARD_AUTH_SECRET": ("auto", "Forward auth cookie secret (32 bytes hex)"),
        },
        "google_oauth": {
            "GOOGLE_CLIENT_ID": ("external", "Google OAuth Client ID"),
            "GOOGLE_CLIENT_SECRET": ("external", "Google OAuth Client Secret"),
            "ADMIN_EMAILS": ("external", "Admin email addresses (comma-separated)"),
        },
        "federation": {
            "HOME_PROMETHEUS_HOST": ("192.168.8.180", "Home Prometheus IP for federation"),
        },
    },
    "home": {
        "general": {
            "COMPOSE_PROJECT_NAME": ("calcifer-home", "Docker Compose project name"),
            "ENVIRONMENT": ("home", "Environment name"),
        },
        "grafana": {
            "GRAFANA_ADMIN_USER": ("admin", "Grafana admin username"),
            "GRAFANA_ADMIN_PASSWORD": ("auto", "Grafana admin password"),
        },
    },
}


def print_header(text: str) -> None:
    """Print a section header."""
    print(f"\n{'─' * 60}")
    print(f"  {text}")
    print(f"{'─' * 60}")


def print_step(icon: str, text: str) -> None:
    """Print a step with icon."""
    print(f"  {icon}  {text}")


def generate_secret(length: int = 32) -> str:
    """Generate a random hex secret."""
    return secrets.token_hex(length)


def generate_password(length: int = 16) -> str:
    """Generate a random alphanumeric password."""
    return secrets.token_urlsafe(length)[:length]


def load_env_file(path: Path) -> Dict[str, str]:
    """Load environment variables from file."""
    env = {}
    if path.exists():
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env[key.strip()] = value.strip()
    return env


def save_env_file(path: Path, env: Dict[str, str], target: str) -> None:
    """Save environment variables to file."""
    sections = ENV_VARS.get(target, {})

    with open(path, "w") as f:
        f.write("# " + "=" * 75 + "\n")
        f.write(f"# Calcifer {target.upper()} Environment Configuration\n")
        f.write("# " + "=" * 75 + "\n")
        f.write("# Auto-generated by calcifer-cli. Do not commit to git.\n\n")

        for section_name, variables in sections.items():
            f.write(f"# {'=' * 20} {section_name.upper().replace('_', ' ')} {'=' * 20}\n")
            for var_name, (_, description) in variables.items():
                if var_name in env:
                    f.write(f"{var_name}={env[var_name]}\n")
            f.write("\n")

        # Add derived variables (ACME_EMAIL)
        if target == "cloud" and "ACME_EMAIL" in env:
            f.write(f"# {'=' * 20} ACME {'=' * 20}\n")
            f.write(f"ACME_EMAIL={env['ACME_EMAIL']}\n")
            f.write("\n")


def prompt_value(var_name: str, description: str, current: Optional[str] = None) -> str:
    """Prompt user for a value."""
    if current:
        prompt = f"  {var_name}\n    {description}\n    Current: {current[:20]}{'...' if len(current) > 20 else ''}\n    New value (Enter to keep): "
    else:
        prompt = f"  {var_name}\n    {description}\n    Value: "
    
    value = input(prompt).strip()
    return value if value else current or ""


def ssh_push_env(target: str, env_content: str) -> bool:
    """Push environment file to remote server."""
    from utils.config import Config
    
    config = Config.load(target=target)
    target_config = config.current_target
    
    remote_path = f"{target_config.deploy_dir}/infrastructure/{target_config.compose_dir}/.env"
    
    # Create remote directory
    ssh_cmd = [
        "ssh", "-i", target_config.ssh_key,
        "-o", "StrictHostKeyChecking=accept-new",
        f"{target_config.user}@{target_config.host}",
        f"mkdir -p {target_config.deploy_dir}/infrastructure/{target_config.compose_dir}"
    ]
    subprocess.run(ssh_cmd, capture_output=True)
    
    # Push file content via stdin
    ssh_cmd = [
        "ssh", "-i", target_config.ssh_key,
        "-o", "StrictHostKeyChecking=accept-new",
        f"{target_config.user}@{target_config.host}",
        f"cat > {remote_path}"
    ]
    result = subprocess.run(ssh_cmd, input=env_content, text=True, capture_output=True)
    return result.returncode == 0


def cmd_env(args: List[str]) -> int:
    """Main env command handler."""
    parser = argparse.ArgumentParser(prog="calcifer-cli.py env")
    parser.add_argument("--target", choices=["home", "cloud"], default="cloud")
    parser.add_argument("--no-prompt", action="store_true",
                        help="Use existing .env file without prompting for missing values")
    opts = parser.parse_args(args)

    target = opts.target
    env_file = CLI_DIR / f".env.{target}"
    no_prompt = opts.no_prompt

    print_header(f"CALCIFER ENVIRONMENT SETUP ({target.upper()})")

    # Load existing env if present
    existing_env = load_env_file(env_file)
    if existing_env:
        print_step("📂", f"Loaded existing config from {env_file.name}")
    else:
        if no_prompt:
            print_step("❌", f"No existing config found and --no-prompt specified!")
            return 1
        print_step("📝", f"No existing config found. Creating new one.")

    # Process all variables
    env = {}
    sections = ENV_VARS.get(target, {})

    for section_name, variables in sections.items():
        print(f"\n  ┌─ {section_name.upper().replace('_', ' ')} ─")

        for var_name, (default, description) in variables.items():
            current = existing_env.get(var_name)

            if default == "auto":
                # Auto-generate secrets
                if current:
                    env[var_name] = current
                    print_step("🔐", f"{var_name}: (kept existing)")
                else:
                    if "SECRET" in var_name or "secret" in var_name.lower():
                        env[var_name] = generate_secret(32)
                    else:
                        env[var_name] = generate_password(16)
                    print_step("🔑", f"{var_name}: (auto-generated)")

            elif default == "external":
                # Prompt for external values (or use existing if --no-prompt)
                if no_prompt:
                    if current:
                        env[var_name] = current
                        print_step("📌", f"{var_name}: (using existing)")
                    else:
                        print_step("⚠️ ", f"Warning: {var_name} not set!")
                else:
                    print()
                    value = prompt_value(var_name, description, current)
                    if value:
                        env[var_name] = value
                    elif current:
                        env[var_name] = current
                    else:
                        print_step("⚠️ ", f"Warning: {var_name} not set!")

            else:
                # Use default or existing
                env[var_name] = current or default
                if current and current != default:
                    print_step("📌", f"{var_name}: {current}")
                else:
                    print_step("📌", f"{var_name}: {default}")

    # Derive ACME_EMAIL from ADMIN_EMAILS (first email)
    if target == "cloud" and "ADMIN_EMAILS" in env:
        admin_emails = env["ADMIN_EMAILS"]
        acme_email = admin_emails.split(",")[0].strip()
        env["ACME_EMAIL"] = acme_email
        print(f"\n  ┌─ ACME ─")
        print_step("📧", f"ACME_EMAIL: {acme_email} (from ADMIN_EMAILS)")

    # Save local file
    print_header("SAVING CONFIGURATION")
    save_env_file(env_file, env, target)
    print_step("💾", f"Saved to {env_file}")

    # Push to server
    print_header("PUSHING TO SERVER")
    print_step("🚀", f"Uploading to {target} server...")

    # Read back the file to push
    with open(env_file) as f:
        env_content = f.read()

    if ssh_push_env(target, env_content):
        print_step("✅", "Configuration pushed successfully!")
    else:
        print_step("❌", "Failed to push configuration!")
        return 1

    print_header("DONE")
    print_step("🎉", f"Environment configured for {target}!")
    print()
    print("  Next steps:")
    print(f"    1. SSH to server and restart services:")
    print(f"       cd /opt/calcifer/infrastructure/{target}")
    print(f"       docker compose up -d --force-recreate")
    print()

    return 0

