apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homepage-security-headers
  namespace: homepage
spec:
  headers:
    contentTypeNosniff: true
    frameDeny: true
    referrerPolicy: no-referrer
