apiVersion: v1
kind: ConfigMap
metadata:
  name: home-edge-wireguard-config
  namespace: private-transit
data:
  wg0.conf.template: |
    [Interface]
    Address = 172.31.255.2/30
    PrivateKey = __PRIVATE_KEY__
    Table = off
    PostUp = ip route replace 172.31.255.1/32 dev %i
    PostUp = iptables -C INPUT -i %i -s 172.31.255.1/32 -p tcp --dport 443 -j ACCEPT || iptables -I INPUT -i %i -s 172.31.255.1/32 -p tcp --dport 443 -j ACCEPT
    PostUp = iptables -C INPUT -i %i -j DROP || iptables -I INPUT -i %i -j DROP
    PostDown = iptables -D INPUT -i %i -j DROP || true
    PostDown = iptables -D INPUT -i %i -s 172.31.255.1/32 -p tcp --dport 443 -j ACCEPT || true
    PostDown = ip route del 172.31.255.1/32 dev %i || true

    [Peer]
    PublicKey = NInZNVXG4GEqDSSpVix202rdD+MiAlOqCkAntgjJdlM=
    Endpoint = 136.144.222.128:51820
    AllowedIPs = 172.31.255.1/32
    PersistentKeepalive = 25
