apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: web
type: Opaque
stringData:
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:cSrE3qkdjq7P5GAwE9Rqzu/ONCIwmoCva3qUqKVRAoiT5FAZfzSG54si45a2HHQIb5P2UlriLxTcSlA82+gL2A==,iv:tfaRp3BlI0VdttlN/FXit1A2k8OqxAxhJSZVlLPVPm8=,tag:RjSlpkCpi5sM1M5MkxmOFg==,type:str]
    HOMEPAGE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:aku2R7YTwD/k/HsuntLEkVJw6HJ36cmKQrceAW622wWbENGJJvJxU7MvdHBeZQzeTtW6LvBZmlc9u75DNtVzBQ==,iv:ydE0QKHCKqQDOb2darWryjpulJX2QyDDVd3T1UBMSgQ=,tag:JK5uFEBKnYm175d+dS7nrw==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMkRSN1pmMms3SzJHRVBr
            N2hlMTNoN1lxdURLdGNtaTR2dnZscEJ3SFFvCjNIRlg2cjdBOWZUOCtOOHBHWlVO
            eTFoY3laNVlIMmZVUXdHdnU2VmZYNkUKLS0tIEErSzdVaWp4K0tSbWtRUi9zZ1ZF
            NEFLWjFWclV2Z3puMk02dTh2MnhPbncKlOpeUbLhA4PPQjww01TMvRUEgajpKXun
            5HDhc/UHjChD5gk43EP2FeaHIArQC2w3Ts5E/8g+mS8hAS6gkZgNhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T11:12:24Z"
    mac: ENC[AES256_GCM,data:oYrwwuQHSLnikKyQJ2ULzIIjK9gWWpgFz8RJB4J9d4f5lelxJ06QR08sR+SwFwo4WKIU8ZoLv8jK2mWn80yhYdlb2kS5zh/LyDldd3ZcS0Z8DkaQWnqlma4jBXhago5AICNkSlkiLKQASd5RDTuva3+EUTlUD4FD9L/JYoqmMnk=,iv:Kejsq3lb/4E/9+En0iGoeHeQOyAkYPT42vhm1fBNjxI=,tag:o9MzUdnMeeIxJvzF21B18Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
