apiVersion: v1
kind: Secret
metadata:
    name: azure-speech
    namespace: home-automation
type: Opaque
stringData:
    AZURE_SERVICE_REGION: ENC[AES256_GCM,data:1pNYnCS6zTSr4Q==,iv:B7WXfJH2ccE7hHvM7G2y7f9BnNxAVqe0EnTJhdf6fA0=,tag:pYQCsvnMStIaY34LGxiKwQ==,type:str]
    AZURE_SUBSCRIPTION_KEY: ENC[AES256_GCM,data:n6cYYSrLl5yIGrERIF0CBYIrN3nySIeNNl4PPc5wdJEeWQcbzE1rNZRYi+RmcBQAl/aD3EXU8ykjq0ReToXl3v13c3xGg5tv++0YW/wiy9ISUHC1,iv:EauGC7Q/zbgv7MlRoamFy1XamYZnPz+LJ2lbbkF76DQ=,tag:f/fTdFJHqP2NGHV42ojj0w==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSW1QbnlNaGVmUGJHUFls
            WWs5RWJBN1ROWitqSG9ucFVuRWp5V2ErRFdFClZ0c2k2NGJ2OWJuNHBSL2kyU29v
            SHlQTFBTV0M1OW1uVDkzOXczV0lVTXMKLS0tIHBjeWFHMTgzOC9GQ3kvLzRSdlZO
            a3prUkRRNTlkc20rMGhhWTVmTTdGRW8KfsZvj18YK6U2VZ9w0gMSxC5y2a4zccj5
            YrT76hCxD86VoMNSDs1Prk99IwryHfWlry7BkQSbrTQeQtMNfLHdwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T11:12:24Z"
    mac: ENC[AES256_GCM,data:7A0MlhxnuR6axxqcboxUj3NBfrzc0Cp6+MXtWMwymDgkHb+CPw8/GusLIqkg26xPXt4UPvZJj3BHj+0rpfaiFChqRqzp10uAMHj1XJar8j1pWLPm41IIEGKmEf9gJv5MQNHybGxey4kX5MwUW9wBfN9si4Pxikefz2qivozhCAE=,iv:4Q4i66vFA3QZLja+jp7Fl1g8VWJZUUDGDvZjJMKbiFU=,tag:15JOIgNt7VGHfKxLF8fNBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
