apiVersion: v1
kind: Secret
metadata:
    name: azuredns-config
    namespace: cert-manager
stringData:
    client-secret: ENC[AES256_GCM,data:uOaDx6EOUYM8L8Jq0p4OQ4Faxw8oQPBjr2BO7IMEMT3CUzqSwK5CXA==,iv:IZTpSTG4hXsfv9SBBuMhz5vprYxAzREzHNbSKloCWZA=,tag:X0CMLuMv2WKN5Pu2pncNYA==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNTFEUjIySWtGMk42K2tV
            N1VHK3ozNkRkYUl6S3ZlZHQ0TGVRcXd1a0RjClZSVWExb2EycG13WVRHaE9ub3Mw
            eGEwVHduUzFmUVY4YklWMzFvc1FhdmsKLS0tIDY1TVBMUGlPdk9Ubmk5Ymlvbzhu
            ak9EYTZaM1AyQmpwZlF3dDZwUzl5dlkKertm3E1XoMpbKbVrwmqtGjXBYtIrYYV+
            dqBwpSfvj6oBbzRlp06xsCG4cGr2qE0rwmGBwlui9Gu2RP5ARlAd7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T07:38:13Z"
    mac: ENC[AES256_GCM,data:vmwltF1YuN6ORymNhhfqpv9texnqmtRE7F+lCkDl81196gVLHLftGA0YalH5YbBx7gZjKqUqDFaLQypLwJGB+MdZGk6gMKERrAp7lh+nBImUGEbPcEMAr91o8291OSITrvWQevg7l+lWEp6f0Ea5vKa0qxrkwctwDQqFEJR07KI=,iv:PiN3EeYGwudTk1yif6jsyPoeqALf4gzTQO3vTcbgqmg=,tag:XJyCLGhEsix/vkv9XSCl3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
