apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
  namespace: authorization
spec:
  template:
    spec:
      containers:
        - name: authorization-server
          image: ghcr.io/dmgiangi/calcifer-authorization-server@sha256:246e52a1009b13ccbfd8e5eb9fb30cbc29afeb92ffb00f739f98329cfb27fb13
