apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
  namespace: authorization
spec:
  template:
    spec:
      containers:
        - name: authorization-server
          image: ghcr.io/dmgiangi/calcifer-authorization-server@sha256:a3ec612f9adb3aafe06d7759d39e3edf58eb2296c552f70bd8fcc03fe0ffcaa2
