---
- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/dmgiangi/calcifer
          icon: github.png
    - Documentation:
        - abbr: DOC
          href: https://gethomepage.dev
          icon: homepage.png

