---
title: Calcifer Cloud
favicon: https://cdn-icons-png.flaticon.com/512/785/785116.png
theme: dark
color: slate
headerStyle: clean
useEqualHeights: true
layout:
  Monitoring:
    style: row
    columns: 2
  Identity:
    style: row
    columns: 1
  Infrastructure:
    style: row
    columns: 1
providers:
  docker: true

