#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
FORCE=false

usage() {
  printf 'Usage: %s [--force]\n' "$(basename "$0")"
  printf 'Generate %s from the current Linux audio session.\n' "$ENV_FILE"
}

case "${1:-}" in
  "") ;;
  --force) FORCE=true ;;
  -h|--help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac

if [[ -e "$ENV_FILE" && "$FORCE" != true ]]; then
  printf 'Error: %s already exists; use --force to replace it.\n' "$ENV_FILE" >&2
  exit 1
fi

user_id="${LVA_USER_ID:-$(id -u)}"
user_group="${LVA_USER_GROUP:-$(id -g)}"
audio_group="${LVA_AUDIO_GROUP:-audio}"
runtime_dir="${LVA_XDG_RUNTIME_DIR:-${XDG_RUNTIME_DIR:-/run/user/$user_id}}"
pulse_server="${LVA_PULSE_SERVER:-${PULSE_SERVER:-$runtime_dir/pulse/native}}"
pulse_cookie="${LVA_PULSE_COOKIE:-$runtime_dir/pulse/cookie}"
lva_port="${LVA_PORT:-6053}"
client_name="${CLIENT_NAME:-linux-voice-assistant}"
output_device="${AUDIO_OUTPUT_DEVICE:-pipewire}"
wake_word_dir="${WAKE_WORD_DIR:-/app/wakewords/custom}"
wake_model="${WAKE_MODEL:-calcifer}"

# These are the devices verified on the Pop!_OS host. They can still be
# overridden with AUDIO_INPUT_DEVICE/AUDIO_OUTPUT_DEVICE when the script is
# used on another host or after an audio-session change.
input_device="${AUDIO_INPUT_DEVICE:-JBL TUNE510BT}"

dotenv_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

input_device_quoted="$(dotenv_quote "$input_device")"
output_device_quoted="$(dotenv_quote "$output_device")"

tmp_file="$(mktemp "$SCRIPT_DIR/.env.tmp.XXXXXX")"
cleanup() {
  rm -f -- "$tmp_file"
}
trap cleanup EXIT

umask 077
cat >"$tmp_file" <<EOF
# Generated by $(basename "$0") on $(date -u +%Y-%m-%dT%H:%M:%SZ)
LVA_USER_ID=$user_id
LVA_USER_GROUP=$user_group
LVA_AUDIO_GROUP=$audio_group
LVA_XDG_RUNTIME_DIR=$runtime_dir
LVA_PULSE_SERVER=$pulse_server
LVA_PULSE_COOKIE=$pulse_cookie
LVA_PORT=$lva_port
CLIENT_NAME=$client_name
AUDIO_INPUT_DEVICE=$input_device_quoted
AUDIO_OUTPUT_DEVICE=$output_device_quoted
WAKE_WORD_DIR=$wake_word_dir
WAKE_MODEL=$wake_model
EOF

chmod 600 "$tmp_file"
mv -- "$tmp_file" "$ENV_FILE"
trap - EXIT

printf 'Generated %s with permissions 0600.\n' "$ENV_FILE"
