apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
  namespace: authorization
spec:
  template:
    spec:
      containers:
        - name: authorization-server
          image: ghcr.io/dmgiangi/calcifer-authorization-server@sha256:e32fee458189e46ce9ca8c43738a737dbae2afa12a39230d19fd2a60c8d7f358
