apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
  namespace: authorization
spec:
  template:
    spec:
      containers:
        - name: authorization-server
          image: ghcr.io/dmgiangi/calcifer-authorization-server@sha256:67ebba06cc607e623eb1590871a78063b9f2b0620f71ecf08f4d903e4ebcbdf6
