apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-backup
    namespace: zigbee2mqtt
type: Opaque
stringData:
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:iCH1PY3LSllze88=,iv:tWNpC4afpZp5LQaLxael5Xl65/qXuPdyfP5P/5FR2OA=,tag:arxIW7WSClE2vGO27M2kVA==,type:str]
    AZURE_ACCOUNT_SAS: ENC[AES256_GCM,data:1sxxo2tR2aQ20N6smmpSRnukfR0o5a2mlBYTV83GCTiP0FWflqfXMKm+zlLqewmr3dELKaDaburIK1ZOhJ+FK8oXlEb2ToATOEyMta7TnGbFRu8YNFsAxuK9AkOM8WDh92QtEGryWL3g4MiqgGl4HrL3uYtYRSUN8d3+9Ij+iZovlutR0i85qXs=,iv:WMR/Ci4eTrX0hOVL+uW0FR8fz+SNOVaYX+fHJ0HZTcs=,tag:jSGmxQc5N4gQUu/ph1EFsQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:wST3XT5mhrHzyfKFk3y4vc+Tl5YspWWnwdYDed3OOWXfLrwjxdhvGRBqMNHxa8V0NAm6oGYb5LISb2Mnd6eQrg==,iv:qfHY1mR4dtkbOYYlk+jdFsyJAPWKW4AkZc2vwnHY9vo=,tag:73RL5MhsycokQGpulnw1bA==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2LzEyK0V5akVyWDAraXkz
            djFhNXB6QnhmV3RXcXBacmxERm9BRUhUL0RjClVWU1VCSGJIZXZGVndaNXVublN2
            VUh3SjRhSFpRdkk1ZHVKbDdySTNrYjQKLS0tIE1iWmdORktIWmkrVlg1T2VkV0lu
            bDlhTTBZZkdiWDF3VEZpb1JKVk1hMncKB7O2GuxvWuVt/JK6Gt0qSDnaGgVdWvwP
            IcF/0iceqaTh977USQ7R+/ujuBaiZqNgrhiC2aaT/SHZ4UMmzdy5BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T04:34:13Z"
    mac: ENC[AES256_GCM,data:+R2Oxeruy1BG8FgrjO2TiAnm5PGoRmGdo++EJBR6gmUf+MP0BaKSULZr1wmds+mp5ChIPABoYo209bLj+5hZBwoJHZ3mbULgiIpU9VBUjoYM2sPlgJdRdfyvl+ZcZQHGVYHri2s39xaSK4rMCybSHRLs/b17OgY9U6esAH5jELU=,iv:K0IutXR8DAitWYcXEZN7z8NkupRcAXsuYdbwn2J8BKA=,tag:O5FAgAL7nv0z5et+s1phHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2