apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-backup
    namespace: zigbee2mqtt
type: Opaque
stringData:
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:pD/21WyVcm1utI7cz5UUlBbpWw==,iv:KyBiVY+e3JKr7os4l2qA+XLzbN/lFcG1h7GrtZCqTYM=,tag:tXTk85hZJN49aqfOTu8TXA==,type:str]
    AZURE_ACCOUNT_SAS: ENC[AES256_GCM,data:gQIYVTbjxtRQZggoSlfwcWJ15GjnefLujwY3mS9RKWpCW7cG3kgqO2dJFeXICGblCcOdLXhDkqwwuswynDBAsQNyZxTey4Gyz99GedJLx0mFVVcKRRyUG8LcZuB3WkByYn3pdEyF7DDEIiu0G6gQXqsi,iv:guOHZ1Z79Ct8Iwl8BMsK/q2/GA5q2a6d3HSVTNiI9oI=,tag:m3cTkwcunyMxSiW6sB9pGQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gF5b3zB1p4VpWnIFZV/V+xmy+Bo4t+zFxXiAN+QwaE1iQP/bymQT/ADhoxKkIQXe/391odoq+7JvakOZtjV5Ng==,iv:FLXdbxVR0w9nuL/ZSR3og032NKAwKP4kK6NmTfQZ4gs=,tag:wYnKy0l7/OE54t5UqkYJaw==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaFh6WGpKdFRtZThxaThN
            NTU1UU5CZ05zY3ZXWE5tQlE0SkM3eXVFUEJnCkkxUVJ3d1JLRlpQT1FQSFJTM25a
            YWRUNVFLK2ZaSmFOanZ0ZU5hYm1jdFUKLS0tIE9TYjhOOHlCcWR2bXBVN3pNcFhH
            c3RZaVpIZXErM2hoMit3K0Nobk5FTEEKGHh1vCCBOSxECfuCJJ6Ot9kBqor+8BJh
            +1kF9oqblaokdEZNeTbQfcPZVtvGA7o/3HifWGcMsVq5mqSZibV6qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T08:31:40Z"
    mac: ENC[AES256_GCM,data:YstqHuY0wIDzHs+PTFO+MRHk6WhNBOX4Nj4QWkIM8zqbPi49mino8Q5nrB2MaS2KnxoDM+6XObpmvnBNC9C7yZ+QdN124Y1WsqvIE3REepLb8/R5qoELEdMn44Ybia3bihgv9O+j657GgNap7VmqVL49LPvqBOv9YEcFv7gtcVM=,iv:OimxffYrR8cdLq5yFe9PJJMKD292GQ+d8dKwfqHCF9E=,tag:6dpAUHAwJ5NjkYvxHBnvSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
