apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secrets
    namespace: zigbee2mqtt
type: Opaque
stringData:
    secret.yaml: ENC[AES256_GCM,data:JLa5smWEqbA6uLmgBRObAVQDkimQa5yi7/yd79EVfYBynIgSE/G8BcEQKu51zHvAXvzY5D5QWR9JRPuxX5gNVGydJvaEa+ThMcFDgpTcZGfJUOARbEjxtwW+wxaX5g5ySp4/I+Rmn1RG+Sitr6mTxs0TMQRy8+ng5KxWD2Q=,iv:qtweR9hq2uX947EFnUcZtM2mq2P02QnO6zGwZAgV2bE=,tag:5gjSqrsTAadYbLGDj/jDMg==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:vgBgnHdOtcR7IcgIVVFcaVaTyDRDddLFSevaDDurbKsJbHrR+XbWiA/2qHOwf2Tvy3DMN9NMo1jnvIDpRaWC9w==,iv:/h2+P7iZ7lnuw85sv7eRq3rF0FuZW7ASVa5GzyOfcSE=,tag:At5PHAj4BnKn7A2qzf25qA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:pq/iQnqUuSYAfkGjqY9IiJ4IVKoH78GPtwBbAhAW8c+gBGGQ5TFO4ZzJ46k=,iv:IdW1tQ1fSg8eff/YC85Lz7joC943Z1NJ6jQpU4xHJLU=,tag:nJO+pOD48Rnva0b0G8DSSg==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ditMRW1oZlpacGJKOGU4
            NCt0MS84a3pCUXY4VEFMc3F3ZUovclJrZ1VBCnUvR0thaHN6Um5yVGJqdWNmc3FQ
            czVmM0lEaEVaTTl6b1l1dkV0dk8xek0KLS0tIE5EZkw3WE1LS2pzUllLek1wVHJv
            UW8rM2hkUGNKVGRIOHdHT21TVkdSTkUKsJWu3EgSPv6EgsFaMYgEd75wmsIg1kWj
            /tR8ovDPfBZaaq15B8vt8AFPDA3ySsK4dx0s3onPHe4qsPa+ubhtTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:03:52Z"
    mac: ENC[AES256_GCM,data:CoJYF7w9CbP+hPCO7HL5uoBrLP1xAir5SgBEJdA7AXpy9aiGufEcYXlK6qbc47mynX2EWh2vPrK8e2AmiUvijF3KkqkRj1HRJ6DBZvscqtxbFGDBl2rV7/D68JoJWMpb0teE5jkpTw9IxYTRXAMGTjha4bPud6R85lYBo3OhFzM=,iv:RDb1nSPQf3xIuDh/meUNOerY/vKuiZZ4G5gDrForxZA=,tag:ZfPfKd4gX38oGRCGVYf38Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
