apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secrets
    namespace: zigbee2mqtt
type: Opaque
stringData:
    secret.yaml: ENC[AES256_GCM,data:uROYWAHNcG9eg5ZEhyAl0Xo2KRc6+nGmnzE9dXY3+l1+aX4q+JMtF0K6hkf50i8ZcnR5K7u9pmP7R3johOIgxB4Q8iRnXAIjq1fyOVKKAr+BQEfhKq7I3Vt5TW1HYNCWZGeNF5hFud6wO5o2B7tHtLPeB5yEB0BlTa0dTsQ=,iv:oMwkra34BQQUzFHZxRO0WfxWA8t74Gp4nu7LSGlyjmE=,tag:2yodN9fPXfYoiUJGXPrq9Q==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSjFDamtZa1d6VHBxOHVI
            V2ZzTFdray9VYnlqdlBEdm4yQmZQYlVYTFU4CkkyaWx2bDVyTlBkd0xiODVRNXZa
            eStrKzJhdFFMNnd5UTVTYkpJa2pyNWcKLS0tIFhpdXA5ZjQrMjNENWlwT2YvVGxp
            cHVNSG03dWw4YzYwejlJNGRkRW5QUlEKH+PmhNTGaO4REERynga+yIkpdGgzK89m
            vJPMmsvU9Q6khTMGIk/d64sxgnc8rthtNo7pYZ+hv7PWrHzLDU4+tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T15:14:04Z"
    mac: ENC[AES256_GCM,data:Z9kWuSYK7OQpPQYYUc4Q01AtBqnewk1MJXeZJAT21efxQBMwaMHQl0VdeoQXzuTqRWq6eST/L69wilaLX+x9RmzgEmPyDPa3rmABduquedUReF3o41h0OkWaPC26nWN/xiwsli5gqwl+ZuhU31M6iiC9hcXXxd9OWWyacKLfOz0=,iv:uvnusmDnPXe2p1ix+vV80yRI+K7wb0iPksWo+CljflM=,tag:4CuNljOs3UDcZACfrKW1vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
