apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-backup
    namespace: home-assistant
type: Opaque
stringData:
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:79Bnpel9EO9b9KIyu93IXp5Nkg==,iv:PyKUNNkr/MXlXHh8Av6eGevnf6srDjeQDRDCXFlC6Ig=,tag:niA/FKHsQ8qvTVE/n4J+hw==,type:str]
    AZURE_ACCOUNT_SAS: ENC[AES256_GCM,data:r9EQT/x7WR69/LfyAJURQAKoTi5gmKYVSWsua4raqdqLPvfcoFP5XP7ky0lJE0QFj9fZh+crcmlKGR9rcl4YwpcO8vc3RphUfTxjt+4YgN9Suu0Rr/nEh3AR+/EP0UgXF+doXcnE4YS1O2T7LKulJA==,iv:XXKXh38e9cRsUIrIe3sxdhQykbTdTDSZPjgiajB7v2Q=,tag:HQnPp7OQPLR6wZw/K8GJqQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:1sgHLQ64bTukZP2olPqD+Zb7kJfdr9HFsUy9J0qdQXtjPz4AbzXOngqT0w+512y8oA3N4nITg/qCluol1frGhQ==,iv:FxduZo96SdbYanrtDJVw5YLj8mGiwKTY5ZEC9l65k+c=,tag:2nxtUI7CfhtLw8rU7xrbqw==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MU5IQjdHMUtsT3daNWUw
            U3ZTWFppaTVETmdCU0dLdGdtdEEzSjU2ZmhFCit1eWFrWWR0dU50QzhBamo4Z0Rh
            TjZKN0QrZmJjd2JEMGNmUFpOVUZWeHMKLS0tIHlpbWJGMXNiYXFmWXdHZGk0QTd3
            aU0wVmtRdGcwSFIvTWNhV1VnMGJtVk0K6RSq3IRlzGJmwRTGZkP2wfUusmf8rG3p
            KHD1pOgZ+pCtarznVXoYWINf8vei7wZ5X85+1+qhk00ak/Wm5IJphw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T08:31:37Z"
    mac: ENC[AES256_GCM,data:w86BkuxCzpw7pdb6ZyDuYcW1z5+AUtLSF3fw2v0Ag/eYITAJlXLyzIKHhjGZz/QC+PDg4OPlvJE2WGEl/c9F2uFSWXUhUGZyQ1WSkTFzt4uioNRKkWThsBGVFc+jaZ2ReVvIrMdI/zb9kFQfsbwpvFEergdDvjoMnxFMtv1ZmWo=,iv:3WiEOVTlL/Uycjy2c/OujzqRQIj8APObKK5p1K7d91E=,tag:/NLa8/Ca/9AfJlK5XCdcjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
