apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-backup
    namespace: home-assistant
type: Opaque
stringData:
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:e5jDpmBBFMf8Mbk=,iv:G48RK424lnR+twSg5uZVR0gInJR921i1so9yUws6jSM=,tag:S27GYaX+yY5HkE+M46RNwA==,type:str]
    AZURE_ACCOUNT_SAS: ENC[AES256_GCM,data:50HMKptnnD0hBcArSHspg5UX9k1ImBuU+q2Z8Qrdy4SARpP4ozjzubmvqomAwYuVQqdRmeAuY5HRVsAVwXt/MD1r3hEphFSTCCbuHBrVSce591MUBK8EM3nvKRwXOsX8xKiN1hiMX3sOLlhO1yi3CQ==,iv:e7AxOzi20OBHA6YSfF1m9OIpOIxNUo950V8R9IeyqCU=,tag:T07Fcpdo6wcU7K6zarzk/Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:HozQhMCndWQ3lKlCfW/gglBnrvNttLUMrc+AWB5zx+eQ2gCDuD5QNiTDCn+quqb95ZbKUQgxpJtuInfYL5BfRw==,iv:vsRI756FUGA9BkBtAxbbGzrmimSen+sihQuv4/Vb2KU=,tag:CXCTHgtQ6eDFJsiOSeDvzw==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSV3ozNmsvRFluVnlYSTFP
            aGZIeCt0ZUFDVGxTc1daV3lsOWVWMlJzZVNNCkV0R3ZMbG9HemZjTWFiVUg3L2dD
            QUQvalM1MmFZTnorWFRzTy9mbVpnODgKLS0tIEFPWG4wanByaHBDOUdoUkM2dWpG
            cmpQQ3pmcTFOT0RnZ2EwVE8xZndUQUkK/M4a19AVnsavEoXQOzjukQn7BDTdJqJB
            I2NjfmJY4hJ8MIv5gwkdOt2FrsBhBe1NH2r8Gnc3fVAmW9z3hrN/3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T15:33:45Z"
    mac: ENC[AES256_GCM,data:u+6QbYrigSilJ2tG9ZF9Zn/jBF9MA5MrriHs0v/6D8h0VenT1YUO5A13+Rw9DpWuY8rCMwrbP/j0PAHZEj9S3kcxdO6dCkF7RLM12N8cnMzxCQx+PH1K3nFOBsM/yrxJD9LAukdGQqjHAhcTnL9M7wv3tQ07/qhnQvD0eY8PsV8=,iv:aibzrw6MQ9rd7ZsWfcF+0DVl4ocx8COmviQhWuDBbgQ=,tag:uiQ3LDxixMGS6tBxrsIBgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
