apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:mAA2hJFmX+cdgnRBEfDlu4IZLbWwLzhds7nwnE8LN1BMMdssdrayQxPmQCgR7SalgL5AUnt4nUZ/05vMSzboNoiuaONMFjT+MnApPmNe0hO4Bzdi2kc2,iv:XvizdBTowcEs/WiKyq1j1qQpIguZe3xtbDLKtFJD6EA=,tag:Qog/1R5r51Z5QoI4XbaOag==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TXpqTnJ0anp1MkQvcElT
            V21VWUhrdHVkKzRaZUdtNVExVlVvaEFsR1NRCnV4WG5ZdytVVDdGdFFJMTk2VzhY
            azJKb09ZOWNKV3FkUkpJc08wLzUzRU0KLS0tIFhTa0dtQnFQbzRWSHZ5b2pSdnJ5
            L2dDQ1JBUnFxMG4yZGpUb3R0dGE4YkUK+LZ4g9WfvOA1+FJGjOWGIcnoe/NYWRzL
            6rQd0+vRfQmefTyHuKqx98rAKxMrHUlT/D9AdorCCaMKPvb0NfedSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T15:19:40Z"
    mac: ENC[AES256_GCM,data:krNyE2ARzmLBsTWoNgvFZxMERmR4LnfiOHPDKITLx/fYEI8xFL4oIrIa6+5LjD5ddyhEqte3hQkM84AF4YYBf7BCheJ3AtOIG7jdwuJXc3xsm/K9aCbesrVX+VLqj/61Ui3eHTmX4AtwZDObiSuiO8XqHDkDynMCkCLJ0sL9h3Q=,iv:y4EOKWQ7Ob97y8h8aVnXsR7En89kUsz6lb+f1989oNc=,tag:pgFylZG4bZsgmqQ9qY76kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
