apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  secretName: zigbee2mqtt-tls
  dnsNames:
    - zigbee.calcifer.tech
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-azure
