apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: thanos
  namespace: monitoring
spec:
  uid: thanos
  resyncPeriod: 5m
  plugins:
    - name: prometheus
      version: 13.1.7
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Thanos
    type: prometheus
    access: proxy
    url: http://thanos-v2-query.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: monitoring
spec:
  uid: loki
  resyncPeriod: 1m
  plugins:
    - name: loki
      version: 13.1.0
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Loki
    type: loki
    access: proxy
    url: http://loki.monitoring.svc.cluster.local:3100
    editable: false
    jsonData:
      maxLines: 1000
      timeout: 60
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-traces
  namespace: monitoring
spec:
  uid: victoria-traces
  resyncPeriod: 1m
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: VictoriaTraces
    type: jaeger
    access: proxy
    url: http://victoria-traces.monitoring.svc.cluster.local:10428/select/jaeger
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
