apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: grafana-api
  namespace: monitoring
spec:
  instanceName: grafana
  resyncPeriod: 1m
  name: grafana-api
  role: Admin
  isDisabled: false
  tokens:
    - name: grafana-api
      secretName: grafana-api-token
      expires: "2027-09-13T00:00:00Z"
