default_config:

homeassistant:
  auth_providers:
    - type: homeassistant

auth_oidc:
  client_id: home-assistant
  client_secret: !secret oidc_client_secret
  discovery_url: https://auth.calcifer.tech/.well-known/openid-configuration
  display_name: Calcifer Authorization Server
  additional_scopes:
    - email
  features:
    default_redirect: true
    include_groups_scope: false
    force_https: true
  claims:
    display_name: email
    username: email
    groups: roles
  roles:
    admin: admin
