apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  endpoints:
    - dnsName: home.calcifer.tech
      recordTTL: 60
      recordType: A
      targets:
        - 192.168.0.102
