apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-automation
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:mAA2hJFmX+cdgnRBEfDlu4IZLbWwLzhds7nwnE8LN1BMMdssdrayQxPmQCgR7SalgL5AUnt4nUZ/05vMSzboNoiuaONMFjT+MnApPmNe0hO4Bzdi2kc2,iv:XvizdBTowcEs/WiKyq1j1qQpIguZe3xtbDLKtFJD6EA=,tag:Qog/1R5r51Z5QoI4XbaOag==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TXpqTnJ0anp1MkQvcElT
            V21VWUhrdHVkKzRaZUdtNVExVlVvaEFsR1NRCnV4WG5ZdytVVDdGdFFJMTk2VzhY
            azJKb09ZOWNKV3FkUkpJc08wLzUzRU0KLS0tIFhTa0dtQnFQbzRWSHZ5b2pSdnJ5
            L2dDQ1JBUnFxMG4yZGpUb3R0dGE4YkUK+LZ4g9WfvOA1+FJGjOWGIcnoe/NYWRzL
            6rQd0+vRfQmefTyHuKqx98rAKxMrHUlT/D9AdorCCaMKPvb0NfedSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T11:12:24Z"
    mac: ENC[AES256_GCM,data:8/H2cOc3A+FBC/d619ELKJWFIyrTxqzKlqcM+pgqVawHBK6YOFEvv5Pzkf7zR1fwiTwnuYD5XfcikaMtGODO/qeucrWanI3LId93Jd3v+VxCHV2/045tH5E67rm/S7/VMRu/triq+zqSXOUwhlaQfsOBQm/gq8o2yCAmwKjPkLc=,iv:Hdf2SWshgoq/Sj3DexVcLCb80X7/7NRmCm8Cn9PP8ug=,tag:OTu3LlqYvqtZ+2A35IUaKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
