apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: home-assistant-configuration
    namespace: home-automation
    files:
      - configuration.yaml
resources:
  - pvc.yaml
  - home-assistant-secrets.sops.yaml
  - backup-secrets.sops.yaml
  - deployment.yaml
  - service.yaml
  - backup-cronjob.yaml
  - certificate.yaml
  - dnsendpoint.yaml
  - traefik.yaml
