apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - wireguard-private-key.sops.yaml
  - wireguard-config.yaml
  - wireguard-daemonset.yaml
  - azure-backup-egress-proxy.yaml
