apiVersion: v1
kind: Secret
metadata:
    name: edge-test-auth
    namespace: edge-test
stringData:
    users: ENC[AES256_GCM,data:FGHo8yyIedNKdb8Uz5rpZjy2roxOpo9qF/Mx/BGwRc9S0PKEjqKosEKQlE3Eu5c=,iv:SGsu1XlanhhjEtYWuC7D5tCcIBfiC8jpOxKdSYE8SXU=,tag:2NXUnS17OcZV/uywK/4ujg==,type:str]
sops:
    age:
        - recipient: age1zrcssj5duesp5x4pnp5rxk96dy378fg68ntpvlyxdhwzcchrvsgqcc9uqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N1hZYjRHaDBhSW0zeDlQ
            Mmg4RStRN0VpZk4vb1pMWUh5TXVDTi8wTUZJCmoyYTdZcTQ0SGRUTFM1bHovdWRY
            czNiMWxJSVdtdWlEY1dwN0hiK0NyVmcKLS0tIDN1c2xDOVFpWElZZjMwRm9UWTNh
            K2R6REp2K0xrUFdyazBPMTAzOTE2eDQKzvIsa5crBra5MuQovYuvKqtHlBRsex9U
            D6had/krmO+52GKctSlxG5LyOKwrRzwmB9HV+bJQ98LalGoL4FwGHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T09:08:34Z"
    mac: ENC[AES256_GCM,data:ImA/NyqPvuq/hdQxsiRCPhZGRTypoW7omMKl/MddOO/cvm58vxyj8i4HCtoIEwg7Wwt7+TiwvLclRxOfHGh9wW14gORoBrzMB4drmhSsIdluSO8O7dfxIf7KiGvgi3qUKeLH2+NeCp1VKrKYrWwORWBIxumMnezv2uslrCrwjxo=,iv:AKLCcvGJs83mWe60tKgy+49cDUXQgnpn4uWXu+GTafg=,tag:ZB903CkVB6nlK6+mlxBsUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
